<?php
require_once'../functions.php';
xiu_get_current_user();
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>Comments &laquo; Admin</title>
  <link rel="stylesheet" href="/static/assets/vendors/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="/static/assets/vendors/font-awesome/css/font-awesome.css">
  <link rel="stylesheet" href="/static/assets/vendors/nprogress/nprogress.css">
  <link rel="stylesheet" href="/static/assets/css/admin.css">
  <script src="/static/assets/vendors/nprogress/nprogress.js"></script>
 <style type="text/css">
 #loading{
   display: none;
   align-items: center;
   justify-content: center;
   position: fixed;
   left: 0;
   right: 0;
   top: 0;
   bottom:0;
   background-color: rgba(0, 0,0, 0.5);
   z-index: 999;
 }
@keyframes ldio-6e14npg0ugq {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-6e14npg0ugq div {
  left: 94px;
  top: 48px;
  position: absolute;
  animation: ldio-6e14npg0ugq linear 1s infinite;
  background: #fe718d;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}.ldio-6e14npg0ugq div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #fe718d;
}.ldio-6e14npg0ugq div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #fe718d;
}
.loadingio-spinner-spinner-4rm7o9bfuhg {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-6e14npg0ugq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-6e14npg0ugq div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
</head>
<body>
  <script>NProgress.start()</script>

  <div class="main">
    <?php include 'inc/navbar.php'; ?>
   
    <div class="container-fluid">
      
      <div class="page-title">
        <h1>所有评论</h1>
      </div>
     
      <div class="page-action">
      
        <div class="btn-batch" style="display: none">
          <button class="btn btn-info btn-sm">批量批准</button>
          <button class="btn btn-warning btn-sm">批量拒绝</button>
          <button class="btn btn-danger btn-sm">批量删除</button>
        </div>
        <ul class="pagination pagination-sm pull-right">
          
        </ul>
      </div>
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th class="text-center" width="40"><input type="checkbox"></th>
            <th>作者</th>
            <th>评论</th>
            <th>评论在</th>
            <th>提交于</th>
            <th>状态</th>
            <th class="text-center" width="150">操作</th>
          </tr>
        </thead>
        <tbody>
         
        </tbody>
      </table>
    </div>
  </div>

  <?php $current_page = 'comments'; ?>
  <?php include 'inc/sidebar.php'; ?>
  <div id="loading">
  <div class="loadingio-spinner-spinner-4rm7o9bfuhg"><div class="ldio-6e14npg0ugq">
<div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
</div></div>
  </div>
 
  <script src="/static/assets/vendors/jquery/jquery.js"></script>
  <script src="/static/assets/vendors/bootstrap/js/bootstrap.js"></script>
  <script src="/static/assets/vendors/jsrender/jsrender.js"></script>
  <script src="/static/assets/vendors/twbs-pagination/jquery.twbsPagination.js"></script>
  <script id="comments_tmpl" type="text/x-jsrender">
{{for comments}}

<tr{{if status == 'held'}} class="warning" {{else status == 'rejected'}} class="danger"{{/if}} data-id="{{:id}}">
            <td class="text-center"><input type="checkbox"></td>
            <td>{{:author}}</td>
            <td>{{:content}}</td>
            <td>《{{:post_title}}》</td>
            <td>{{:created}}</td>
            <td>{{:status}}</td>
            <td class="text-center">
              {{if status =='held'}}
              <a href="post-add.html" class="btn btn-info btn-xs">批准</a>
              <a href="post-add.html" class="btn btn-warning btn-xs">拒绝</a>
              {{/if}}
              <a href="javascript:;" class="btn btn-danger btn-xs btn-delete">删除</a>
            </td>
          </tr>
{{/for}}
  </script>
  <script>
  //发送AJAX请求获取列表数据，将数据渲染到页面
  var currentPage = 1;
  function loadPageData(page){
    $('tbody').fadeOut()
    $.get("/admin/api/comments.php",{ page: page }, function(res){
   
      if(page>res.total_pages){
       loadPageData(res.total_pages)
      return
}
$('.pagination').twbsPagination('destroy')
      $('.pagination').twbsPagination({
        first:'&laquo;',
        last:'&raquo;',
        prev:'&lt;',
        next:'&gt;',
        startPage:page,
totalPages: res.total_pages,
visiablePages: 5,
initiateStartPageClick:false,
onPageClick:function(e,page){
  loadPageData(page)
  
}
  });
    var html=$('#comments_tmpl').render({comments:res.comments})
    $('tbody').html(html).fadeIn();
    currentPage=page;
      });
  }
  loadPageData(currentPage)
 
  //删除功能，事件委托
  $('tbody').on('click','.btn-delete',function(){
//1.拿到要删除的数据id
var tr=$(this).parent().parent()
var id =tr.data('id');
//2.发送一个AJAX请求告诉服务端要删除那一条具体的数据
$.get('/admin/api/comments-delete.php',{ id : id},function(res){
 
if(!res) return;
  loadPageData(currentPage)

})
//3.根据服务器返回的删除是否成功在界面上删除
  });
  </script>
  <script>
  $(document).ajaxStart(function(){
    NProgress.start()
    $('#loading').css('display','flex')
  }).ajaxStop(function(){
    NProgress.done()
    $('#loading').css('display','none')
  });
 
  </script>
</body>
</html>
